service: glibc-bug

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: letscrash
 
custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements