service: glibc-bug

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

  deploymentBucket:
    name: ${ssm:/infra/buckets/Deploy}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: letscrash
 
custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.11:latest-x86_64

plugins:
  - serverless-python-requirements